import Head from 'next/head'
import Image from 'next/image'
import Main from '../components/Main'
import Navbar from '../components/Navbar'
import About from '../components/About'
import Work from '../components/Work'
import Contact from '../components/Contact'
import { useEffect, useState } from 'react'
import {HashLoader} from 'react-spinners'
import Footer from '../components/Footer'

function Home() {

  const [loading, setLoading] = useState(true)

  useEffect(() => {
    setLoading(true);
    setTimeout(() => {
      setLoading(false)
    }, 1000)


  }, [])
  return (
    <div className='bg-black/30'>
      {loading ?
        <>
          <HashLoader
          style={{}}
            color="#03fcdb"
            loading={loading}
            size={150}
            speedMultiplier={1}
          />
        </> :
            <div className=''>
          <Head>
            <title>Stephen | Softare Engineer</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/logo.svg" />
          </Head>
          <Navbar />
          <Main />
          <About />
          <Work />
          <Contact />
          <Footer />
     
        </div>}
    </div>
  )
}

export default Home